<%@ Page Title="" Language="C#" MasterPageFile="~/View/MasterPage.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="MasterApp.View.Home" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
        <div class="row">
            <div class="col-lg-12" style="text-align:center;">
                <h1><asp:Label Text="VIEW STUDENTS" runat="server" ForeColor="White"></asp:Label></h1>
            </div>
            <div class="col-lg-2"></div>
            <div class="col-lg-10">
                <div class="studentTable" style="padding-left:8%; padding-top:5em; text-align:center;">
                    <table>
                        <tr>
                            <th>&nbsp;</th>
                            <td><asp:TextBox ID="txtSearch" CssClass="form-control input-md" runat="server" Width="130px"></asp:TextBox></td>
                            <td style="padding-left:5px;"><asp:Button runat="server" CssClass="btn-danger" Text="Search Course" ID="btnSearch" OnClick="btnSearch_Click" /></td>
                            <td><asp:Button runat="server" CssClass="btn-secondary" Text="All Course" ID="btnAll" OnClick="btnAll_Click" /></td>
                        </tr>
                    </table>
                
                    <asp:GridView ID="GridView1" style="white-space: nowrap; overflow: hidden; text-align:center; width:80%; padding-left:20%;" runat="server" AutoGenerateColumns="False"   
                            BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px"   
                            CellPadding="4" DataKeyNames="id" AutoGenerateDeleteButton="True"   
                            AutoGenerateEditButton="True"  onrowcancelingedit="GridView1_RowCancelingEdit"   
                            onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
                            onrowupdating="GridView1_RowUpdating" AllowPaging="True" AllowSorting="True" PageSize="5" ForeColor="Black" GridLines="Horizontal">  
                                <HeaderStyle Width="10%" BackColor="#333333" />
                                <RowStyle Width="10%" />
                                <FooterStyle Width="10%" BackColor="#CCCC99" ForeColor="Black" />
                                <Columns>  
 
                                    <asp:TemplateField ItemStyle-HorizontalAlign="Left" HeaderText="Name" HeaderStyle-ForeColor="White" HeaderStyle-Width="30%">  
                                        <EditItemTemplate>  
                                            <asp:TextBox ID="txtBoxName" runat="server" Text='<%# Bind("s_name") %>'></asp:TextBox>  
                                        </EditItemTemplate>  
                                        <ItemTemplate>  
                                            <asp:Label ID="lblName" runat="server" Text='<%# Bind("s_name") %>'></asp:Label>  
                                        </ItemTemplate>  

<HeaderStyle ForeColor="White" Width="30%"></HeaderStyle>

<ItemStyle HorizontalAlign="Left"></ItemStyle>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Age"  HeaderStyle-ForeColor="White" HeaderStyle-Width="10%">  
                                        <EditItemTemplate>  
                                            <asp:TextBox ID="txtBoxAge" runat="server" Text='<%# Bind("s_age") %>'></asp:TextBox>  
                                        </EditItemTemplate>  
                                        <ItemTemplate>  
                                            <asp:Label ID="lblAge" runat="server" Text='<%# Bind("s_age") %>'></asp:Label>  
                                        </ItemTemplate>  

<HeaderStyle ForeColor="White" Width="10%"></HeaderStyle>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Roll No"  HeaderStyle-ForeColor="White" HeaderStyle-Width="10%">  
                                        <EditItemTemplate>  
                                            <asp:TextBox ID="txtBoxRoll" runat="server" Text='<%# Bind("s_roll") %>'></asp:TextBox>  
                                        </EditItemTemplate>  
                                        <ItemTemplate>  
                                            <asp:Label ID="lblRoll" runat="server" Text='<%# Bind("s_roll") %>'></asp:Label>  
                                        </ItemTemplate>  

<HeaderStyle ForeColor="White" Width="10%"></HeaderStyle>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Course"  HeaderStyle-ForeColor="White" HeaderStyle-Width="10%">  
                                        <EditItemTemplate>  
                                            <asp:TextBox ID="txtBoxCourse" runat="server" Text='<%# Bind("s_course") %>'></asp:TextBox>  
                                        </EditItemTemplate>  
                                        <ItemTemplate>  
                                            <asp:Label ID="lblCourse" runat="server" Text='<%# Bind("s_course") %>'></asp:Label>  
                                        </ItemTemplate>  

<HeaderStyle ForeColor="White" Width="10%"></HeaderStyle>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Address"  HeaderStyle-ForeColor="White" HeaderStyle-Width="40%">  
                                        <EditItemTemplate>  
                                            <asp:TextBox ID="txtBoxAddress" runat="server" Text='<%# Bind("s_address") %>'></asp:TextBox>  
                                        </EditItemTemplate>  
                                        <ItemTemplate>  
                                            <asp:Label ID="lblAddress" runat="server" Text='<%# Bind("s_address") %>'></asp:Label>  
                                        </ItemTemplate>  

<HeaderStyle ForeColor="White" Width="40%"></HeaderStyle>
                                    </asp:TemplateField>
                                </Columns>  
                                <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />  
                                <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />  
                                <PagerStyle ForeColor="Black" HorizontalAlign="Right" BackColor="White" />  
                                <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />  
                                <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />  
                                <SortedAscendingCellStyle BackColor="#F7F7F7" />  
                                <SortedAscendingHeaderStyle BackColor="#4B4B4B" />  
                                <SortedDescendingCellStyle BackColor="#E5E5E5" />  
                                <SortedDescendingHeaderStyle BackColor="#242121" />  
                            </asp:GridView>
                </div>
            </div>
            <div class="col-lg-2"></div>
            
        </div>
        
        </div>
</asp:Content>
